require('globals')
require('plugins')
require('keymaps')
require('settings')
require('appearance')
require('plugins.lsp')
require('plugins.galaxyline')
require('plugins.nvim-tree')
require('plugins.telescope')

